#!/usr/bin/env bash

set +x

sudo lxc-ls -f | awk '/remissionorguk/ {print $5}' 2>/dev/null > local

ansible-playbook --inventory local \
                 --user vagrant \
                 --private-key ~/.vagrant.d/insecure_private_key \
                 playbook.yml \
                 "$@"
